### ISSUE TITLE
Admin Access.

### ISSUE THREAD

**Issue by Mugerwa-Joseph** [SanjulaD/web-cw#2]
How does the admin get to access the control panel?
Assuming the admin wants to cancel an order placed by the consumer, or the admin wants to register new users, how does he/she go over that?

Otherwise, this is a cool project. Your efforts are highly appreciated..

**Comment by SanjulaD** [comment]
You meant the hosted application or the development side??

**Comment by Mugerwa-Joseph** [comment]
I was meaning the development side.

But I have figured my way out.
Though it is manual and may not be recommendable, I had to tweak the userModel.js isAdmin field and made the default true, then created a normal consumer client who then became an admin. I thereafter took back the isAdmin boolean field in the userModel.js to false default.

That has solved my issue.

I highly appreciate the efforts invested by @SanjulaD 

Cheers.

**Comment by SanjulaD** [comment]
Awesome, thanks!. From that boolean value you can change the admin
